::Check for wad file. If it's not there, jump out
if not exist "%~3\TNT.WAD" (
    echo TNT.WAD not found. Skipping... >&2
    type "%~5\TEXTURES.tnt.dummy" >> "%~2\TEXTURES.txt"
    EXIT /B %ERRORLEVEL%
)

cd "%~5"

::Copy our installer files
type "ANIMDEFS.tnt.prt" >> "%~2\ANIMDEFS.txt"
type "TEXTURES.tnt.prt" >> "%~2\TEXTURES.txt"
type "MAPINFO.tnt.prt" >> "%~2\MAPINFO.txt"
type "CVARINFO.tnt.prt" >> "%~2\CVARINFO.txt"

::Extract Files
::=======================
::call "%~1\display_section.cmd" Doom 1 >&2
echo Fetching data from TNT.WAD... >&2
if not exist "%~3\tnt" mkdir "%~3\tnt"
cd "%~3\tnt"
call %4 "%~3\TNT.WAD"
echo Copying data to %~2... >&2

::copy over necessary graphics
::=============================
::misc graphics
copy ".\graphics\interpic.png" "%~2\graphics\tnterpic.png"
copy ".\graphics\bossback.png" "%~2\graphics\tossback.png"


::Copy Over Patches
::=======================
copy ".\patches\doenite.png" "%~2\patches\doenite.png"
copy ".\patches\donnite.png" "%~2\patches\donnite.png"
copy ".\patches\downite.png" "%~2\patches\downite.png"
copy ".\patches\dosnite.png" "%~2\patches\dosnite.png"
copy ".\patches\doehell.png" "%~2\patches\doehell.png"
copy ".\patches\donhell.png" "%~2\patches\donhell.png"
copy ".\patches\dowhell.png" "%~2\patches\dowhell.png"
copy ".\patches\doshell.png" "%~2\patches\doshell.png"
copy ".\patches\doeday.png" "%~2\patches\doeday.png"
copy ".\patches\donday.png" "%~2\patches\donday.png"
copy ".\patches\dowday.png" "%~2\patches\dowday.png"
copy ".\patches\dosday.png" "%~2\patches\dosday.png"
copy ".\patches\blod64a.png" "%~2\patches\blod64a.png"
copy ".\patches\blod64b.png" "%~2\patches\blod64b.png"
copy ".\patches\blod128a.png" "%~2\patches\blod128a.png"
copy ".\patches\blod128b.png" "%~2\patches\blod128b.png"
copy ".\patches\crlwdh6.png" "%~2\patches\crlwdh6.png"
copy ".\patches\crlwdl6.png" "%~2\patches\crlwdl6.png"
copy ".\patches\crlwdl6b.png" "%~2\patches\crlwdl6b.png"
copy ".\patches\crlwdl6c.png" "%~2\patches\crlwdl6c.png"
copy ".\patches\crlwdl6d.png" "%~2\patches\crlwdl6d.png"
copy ".\patches\crlwdl6e.png" "%~2\patches\crlwdl6e.png"
copy ".\patches\crlwdl12.png" "%~2\patches\crlwdl12.png"
copy ".\patches\crlwds6.png" "%~2\patches\crlwds6.png"
copy ".\patches\crlwdt3.png" "%~2\patches\crlwdt3.png"
copy ".\patches\crwdh6.png" "%~2\patches\crwdh6.png"
copy ".\patches\crwdh6b.png" "%~2\patches\crwdh6b.png"
copy ".\patches\crwdl6b.png" "%~2\patches\crwdl6b.png"
copy ".\patches\crwdl6c.png" "%~2\patches\crwdl6c.png"
copy ".\patches\crwdl6d.png" "%~2\patches\crwdl6d.png"
copy ".\patches\crwdl12.png" "%~2\patches\crwdl12.png"
copy ".\patches\crwds6.png" "%~2\patches\crwds6.png"
copy ".\patches\crwdt3.png" "%~2\patches\crwdt3.png"
copy ".\patches\crwdvs3.png" "%~2\patches\crwdvs3.png"
copy ".\patches\bul64a.png" "%~2\patches\bul64a.png"
copy ".\patches\bul64b.png" "%~2\patches\bul64b.png"
copy ".\patches\bul64c.png" "%~2\patches\bul64c.png"
copy ".\patches\bul64d.png" "%~2\patches\bul64d.png"
copy ".\patches\btntcrat.png" "%~2\patches\btntcrat.png"
copy ".\patches\romero1.png" "%~2\patches\romero1.png"
copy ".\patches\smcratg.png" "%~2\patches\smcratg.png"
copy ".\patches\dogldir.png" "%~2\patches\dogldir.png"
copy ".\patches\dokodo1b.png" "%~2\patches\dokodo1b.png"
copy ".\patches\dokodo2b.png" "%~2\patches\dokodo2b.png"
copy ".\patches\dobwire.png" "%~2\patches\dobwire.png"
copy ".\patches\dobwire2.png" "%~2\patches\dobwire2.png"
copy ".\patches\eggreeni.png" "%~2\patches\eggreeni.png"
copy ".\patches\egredi.png" "%~2\patches\egredi.png"
copy ".\patches\yellite1.png" "%~2\patches\yellite1.png"
copy ".\patches\yellite2.png" "%~2\patches\yellite2.png"
copy ".\patches\yellite3.png" "%~2\patches\yellite3.png"
copy ".\patches\yeltnt.png" "%~2\patches\yeltnt.png"
copy ".\patches\grnlit1.png" "%~2\patches\grnlit1.png"
copy ".\patches\redlite1.png" "%~2\patches\redlite1.png"
copy ".\patches\redlite2.png" "%~2\patches\redlite2.png"
copy ".\patches\dored.png" "%~2\patches\dored.png"
copy ".\patches\dotntdr.png" "%~2\patches\dotntdr.png"
copy ".\patches\altaqua.png" "%~2\patches\altaqua.png"
copy ".\patches\asphalt.png" "%~2\patches\asphalt.png"
copy ".\patches\cyan.png" "%~2\patches\cyan.png"
copy ".\patches\dobigtva.png" "%~2\patches\dobigtva.png"
copy ".\patches\dobigtvb.png" "%~2\patches\dobigtvb.png"
copy ".\patches\dobigtvc.png" "%~2\patches\dobigtvc.png"
copy ".\patches\dobigtvd.png" "%~2\patches\dobigtvd.png"
copy ".\patches\doblip1a.png" "%~2\patches\doblip1a.png"
copy ".\patches\doblip2a.png" "%~2\patches\doblip2a.png"
copy ".\patches\doblip3a.png" "%~2\patches\doblip3a.png"
copy ".\patches\doblip4a.png" "%~2\patches\doblip4a.png"
copy ".\patches\doslvr11.png" "%~2\patches\doslvr11.png"
copy ".\patches\doslvr12.png" "%~2\patches\doslvr12.png"
copy ".\patches\doslvr13.png" "%~2\patches\doslvr13.png"
copy ".\patches\doslvr14.png" "%~2\patches\doslvr14.png"
copy ".\patches\doslvr21.png" "%~2\patches\doslvr21.png"
copy ".\patches\doslvr22.png" "%~2\patches\doslvr22.png"
copy ".\patches\doslvr23.png" "%~2\patches\doslvr23.png"
copy ".\patches\doslvr24.png" "%~2\patches\doslvr24.png"
copy ".\patches\dospi1b.png" "%~2\patches\dospi1b.png"
copy ".\patches\dospi2b.png" "%~2\patches\dospi2b.png"
copy ".\patches\dospi3b.png" "%~2\patches\dospi3b.png"
copy ".\patches\dospi4b.png" "%~2\patches\dospi4b.png"
copy ".\patches\dosw1.png" "%~2\patches\dosw1.png"
copy ".\patches\dosw1c.png" "%~2\patches\dosw1c.png"
copy ".\patches\dosw2.png" "%~2\patches\dosw2.png"
copy ".\patches\dosw2c.png" "%~2\patches\dosw2c.png"
copy ".\patches\dosw3.png" "%~2\patches\dosw3.png"
copy ".\patches\dosw3c.png" "%~2\patches\dosw3c.png"
copy ".\patches\dosw4.png" "%~2\patches\dosw4.png"
copy ".\patches\dosw4c.png" "%~2\patches\dosw4c.png"
copy ".\patches\doswx1.png" "%~2\patches\doswx1.png"
copy ".\patches\doswx1c.png" "%~2\patches\doswx1c.png"
copy ".\patches\doswx2.png" "%~2\patches\doswx2.png"
copy ".\patches\doswx2c.png" "%~2\patches\doswx2c.png"
copy ".\patches\doswx3.png" "%~2\patches\doswx3.png"
copy ".\patches\doswx3c.png" "%~2\patches\doswx3c.png"
copy ".\patches\doswx4.png" "%~2\patches\doswx4.png"
copy ".\patches\doswx4c.png" "%~2\patches\doswx4c.png"
copy ".\patches\dotv1b.png" "%~2\patches\dotv1b.png"
copy ".\patches\dotv2b.png" "%~2\patches\dotv2b.png"
copy ".\patches\dotv3b.png" "%~2\patches\dotv3b.png"
copy ".\patches\dotv4b.png" "%~2\patches\dotv4b.png"
copy ".\patches\dowebl.png" "%~2\patches\dowebl.png"
copy ".\patches\dowebr.png" "%~2\patches\dowebr.png"
copy ".\patches\dowindow.png" "%~2\patches\dowindow.png"
copy ".\patches\drfront.png" "%~2\patches\drfront.png"
copy ".\patches\drside1.png" "%~2\patches\drside1.png"
copy ".\patches\drside2.png" "%~2\patches\drside2.png"
copy ".\patches\drtopfr.png" "%~2\patches\drtopfr.png"
copy ".\patches\drtopsid.png" "%~2\patches\drtopsid.png"
copy ".\patches\fence4.png" "%~2\patches\fence4.png"
copy ".\patches\fence5.png" "%~2\patches\fence5.png"
copy ".\patches\grnopen.png" "%~2\patches\grnopen.png"
copy ".\patches\longwall.png" "%~2\patches\longwall.png"
copy ".\patches\mtnt2.png" "%~2\patches\mtnt2.png"
copy ".\patches\mural1.png" "%~2\patches\mural1.png"
copy ".\patches\mural2.png" "%~2\patches\mural2.png"
copy ".\patches\pblak.png" "%~2\patches\pblak.png"
copy ".\patches\pcwinl.png" "%~2\patches\pcwinl.png"
copy ".\patches\pillar.png" "%~2\patches\pillar.png"
copy ".\patches\pivy3.png" "%~2\patches\pivy3.png"
copy ".\patches\pl_01.png" "%~2\patches\pl_01.png"
copy ".\patches\pl_05.png" "%~2\patches\pl_05.png"
copy ".\patches\pl_10.png" "%~2\patches\pl_10.png"
copy ".\patches\pl_18.png" "%~2\patches\pl_18.png"
copy ".\patches\pl_19.png" "%~2\patches\pl_19.png"
copy ".\patches\pl_20.png" "%~2\patches\pl_20.png"
copy ".\patches\pl_25.png" "%~2\patches\pl_25.png"
copy ".\patches\pl_31.png" "%~2\patches\pl_31.png"
copy ".\patches\pl_a.png" "%~2\patches\pl_a.png"
copy ".\patches\pl_c.png" "%~2\patches\pl_c.png"
copy ".\patches\pl_n.png" "%~2\patches\pl_n.png"
copy ".\patches\pl_t.png" "%~2\patches\pl_t.png"
copy ".\patches\pl_u.png" "%~2\patches\pl_u.png"
copy ".\patches\preel1.png" "%~2\patches\preel1.png"
copy ".\patches\preel2.png" "%~2\patches\preel2.png"
copy ".\patches\preel3.png" "%~2\patches\preel3.png"
copy ".\patches\preel4.png" "%~2\patches\preel4.png"
copy ".\patches\preel5.png" "%~2\patches\preel5.png"
copy ".\patches\preel6.png" "%~2\patches\preel6.png"
copy ".\patches\preel7.png" "%~2\patches\preel7.png"
copy ".\patches\pston2.png" "%~2\patches\pston2.png"
copy ".\patches\redopen.png" "%~2\patches\redopen.png"
copy ".\patches\redtnt2.png" "%~2\patches\redtnt2.png"
copy ".\patches\saw1.png" "%~2\patches\saw1.png"
copy ".\patches\saw1sd.png" "%~2\patches\saw1sd.png"
copy ".\patches\saw2.png" "%~2\patches\saw2.png"
copy ".\patches\saw2sd.png" "%~2\patches\saw2sd.png"
copy ".\patches\saw3.png" "%~2\patches\saw3.png"
copy ".\patches\saw3sd.png" "%~2\patches\saw3sd.png"
copy ".\patches\saw4.png" "%~2\patches\saw4.png"
copy ".\patches\saw4sd.png" "%~2\patches\saw4sd.png"
copy ".\patches\saw5.png" "%~2\patches\saw5.png"
copy ".\patches\saw5sd.png" "%~2\patches\saw5sd.png"
copy ".\patches\saw6.png" "%~2\patches\saw6.png"
copy ".\patches\saw6sd.png" "%~2\patches\saw6sd.png"
copy ".\patches\skirting.png" "%~2\patches\skirting.png"
copy ".\patches\smfiller.png" "%~2\patches\smfiller.png"
copy ".\patches\stonew1.png" "%~2\patches\stonew1.png"
copy ".\patches\stonew5.png" "%~2\patches\stonew5.png"
copy ".\patches\stwall.png" "%~2\patches\stwall.png"
copy ".\patches\tyunder1.png" "%~2\patches\tyunder1.png"
copy ".\patches\tywheel1.png" "%~2\patches\tywheel1.png"
copy ".\patches\tywfall1.png" "%~2\patches\tywfall1.png"
copy ".\patches\tywfall2.png" "%~2\patches\tywfall2.png"
copy ".\patches\tywfall3.png" "%~2\patches\tywfall3.png"
copy ".\patches\tywfall4.png" "%~2\patches\tywfall4.png"
copy ".\patches\tywfall1.png" "%~2\patches\wfall1.png"
copy ".\patches\tywfall2.png" "%~2\patches\wfall2.png"
copy ".\patches\tywfall3.png" "%~2\patches\wfall3.png"
copy ".\patches\tywfall4.png" "%~2\patches\wfall4.png"
copy ".\patches\bigmural.png" "%~2\patches\bigmural.png"
copy ".\patches\bigwall.png" "%~2\patches\bigwall.png"
copy ".\patches\brnopen.png" "%~2\patches\brnopen.png"
copy ".\patches\carllf1.png" "%~2\patches\carllf1.png"
copy ".\patches\carllf2.png" "%~2\patches\carllf2.png"
copy ".\patches\carlrt1.png" "%~2\patches\carlrt1.png"
copy ".\patches\carlrt2.png" "%~2\patches\carlrt2.png"
copy ".\patches\cavern1.png" "%~2\patches\cavern1.png"
copy ".\patches\cavern4.png" "%~2\patches\cavern4.png"
copy ".\patches\cavern5.png" "%~2\patches\cavern5.png"
copy ".\patches\cavern6.png" "%~2\patches\cavern6.png"
copy ".\patches\cavern7.png" "%~2\patches\cavern7.png"
copy ".\patches\clwdvs3.png" "%~2\patches\clwdvs3.png"
copy ".\patches\doglpanl.png" "%~2\patches\doglpanl.png"
copy ".\patches\dogrid.png" "%~2\patches\dogrid.png"
copy ".\patches\dogrmsc.png" "%~2\patches\dogrmsc.png"
copy ".\patches\dogrnmen.png" "%~2\patches\dogrnmen.png"
copy ".\patches\dokgrir.png" "%~2\patches\dokgrir.png"
copy ".\patches\dopunk4.png" "%~2\patches\dopunk4.png"
copy ".\patches\bcrat32.png" "%~2\patches\bcrat32.png"
copy ".\patches\bcrat16.png" "%~2\patches\bcrat16.png"
copy ".\patches\dosha1.png" "%~2\patches\dosha1.png"
copy ".\patches\doshb1.png" "%~2\patches\doshb1.png"
copy ".\patches\doshc1.png" "%~2\patches\doshc1.png"
copy ".\patches\doshd1.png" "%~2\patches\doshd1.png"
copy ".\patches\doshe1.png" "%~2\patches\doshe1.png"
copy ".\patches\doshf1.png" "%~2\patches\doshf1.png"
copy ".\patches\blutnt.png" "%~2\patches\blutnt.png"

::Copy Over Maps
::=================
copy ".\maps\MAP01.WAD" "%~2\maps\TNT01.wad"
copy ".\maps\MAP02.WAD" "%~2\maps\TNT02.wad"
copy ".\maps\MAP03.WAD" "%~2\maps\TNT03.wad"
copy ".\maps\MAP04.WAD" "%~2\maps\TNT04.wad"
copy ".\maps\MAP05.WAD" "%~2\maps\TNT05.wad"
copy ".\maps\MAP06.WAD" "%~2\maps\TNT06.wad"
copy ".\maps\MAP07.WAD" "%~2\maps\TNT07.wad"
copy ".\maps\MAP08.WAD" "%~2\maps\TNT08.wad"
copy ".\maps\MAP09.WAD" "%~2\maps\TNT09.wad"
copy ".\maps\MAP10.WAD" "%~2\maps\TNT10.wad"
copy ".\maps\MAP11.WAD" "%~2\maps\TNT11.wad"
copy ".\maps\MAP12.WAD" "%~2\maps\TNT12.wad"
copy ".\maps\MAP13.WAD" "%~2\maps\TNT13.wad"
copy ".\maps\MAP14.WAD" "%~2\maps\TNT14.wad"
copy ".\maps\MAP15.WAD" "%~2\maps\TNT15.wad"
copy ".\maps\MAP16.WAD" "%~2\maps\TNT16.wad"
copy ".\maps\MAP17.WAD" "%~2\maps\TNT17.wad"
copy ".\maps\MAP18.WAD" "%~2\maps\TNT18.wad"
copy ".\maps\MAP19.WAD" "%~2\maps\TNT19.wad"
copy ".\maps\MAP20.WAD" "%~2\maps\TNT20.wad"
copy ".\maps\MAP21.WAD" "%~2\maps\TNT21.wad"
copy ".\maps\MAP22.WAD" "%~2\maps\TNT22.wad"
copy ".\maps\MAP23.WAD" "%~2\maps\TNT23.wad"
copy ".\maps\MAP24.WAD" "%~2\maps\TNT24.wad"
copy ".\maps\MAP25.WAD" "%~2\maps\TNT25.wad"
copy ".\maps\MAP26.WAD" "%~2\maps\TNT26.wad"
copy ".\maps\MAP27.WAD" "%~2\maps\TNT27.wad"
copy ".\maps\MAP28.WAD" "%~2\maps\TNT28.wad"
copy ".\maps\MAP29.WAD" "%~2\maps\TNT29.wad"
copy ".\maps\MAP30.WAD" "%~2\maps\TNT30.wad"
copy ".\maps\MAP31.WAD" "%~2\maps\TNT31.wad"
copy ".\maps\MAP32.WAD" "%~2\maps\TNT32.wad"


::Copy Over Music
::=================
copy ".\music\d_runnin.mus" "%~2\music\d_tnt01.mus"
copy ".\music\d_stalks.mus" "%~2\music\d_tnt02.mus"
copy ".\music\d_countd.mus" "%~2\music\d_tnt03.mus"
copy ".\music\d_betwee.mus" "%~2\music\d_tnt04.mus"
copy ".\music\d_doom.mus" "%~2\music\d_tnt05.mus"
copy ".\music\d_the_da.mus" "%~2\music\d_tnt06.mus"
copy ".\music\d_shawn.mus" "%~2\music\d_tnt07.mus"
copy ".\music\d_ddtblu.mus" "%~2\music\d_tnt08.mus"
copy ".\music\d_in_cit.mus" "%~2\music\d_tnt09.mus"
copy ".\music\d_dead.mus" "%~2\music\d_tnt10.mus"
copy ".\music\d_stlks2.mus" "%~2\music\d_tnt11.mus"
copy ".\music\d_theda2.mus" "%~2\music\d_tnt12.mus"
copy ".\music\d_doom2.mus" "%~2\music\d_tnt13.mus"
copy ".\music\d_ddtbl2.mus" "%~2\music\d_tnt14.mus"
copy ".\music\d_runni2.mus" "%~2\music\d_tnt15.mus"
copy ".\music\d_dead2.mus" "%~2\music\d_tnt16.mus"
copy ".\music\d_stlks3.mus" "%~2\music\d_tnt17.mus"
copy ".\music\d_romero.mus" "%~2\music\d_tnt18.mus"
copy ".\music\d_shawn2.mus" "%~2\music\d_tnt19.mus"
copy ".\music\d_messag.mus" "%~2\music\d_tnt20.mus"
copy ".\music\d_count2.mus" "%~2\music\d_tnt21.mus"
copy ".\music\d_ddtbl3.mus" "%~2\music\d_tnt22.mus"
copy ".\music\d_ampie.mus" "%~2\music\d_tnt23.mus"
copy ".\music\d_theda3.mus" "%~2\music\d_tnt24.mus"
copy ".\music\d_adrian.mus" "%~2\music\d_tnt25.mus"
copy ".\music\d_messg2.mus" "%~2\music\d_tnt26.mus"
copy ".\music\d_romer2.mus" "%~2\music\d_tnt27.mus"
copy ".\music\d_tense.mus" "%~2\music\d_tnt28.mus"
copy ".\music\d_shawn3.mus" "%~2\music\d_tnt29.mus"
copy ".\music\d_openin.mus" "%~2\music\d_tnt30.mus"
copy ".\music\d_ultima.mus" "%~2\music\d_tnt32.mus"
copy ".\music\d_dm2int.mus" "%~2\music\d_tntint.mus"
copy ".\music\d_read_m.mus" "%~2\music\d_tntre.mus"
